# Linear Regression Algorithm

### Import Libraries

In [7]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sb 
import sklearn 
from sklearn import datasets
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error , mean_squared_error , r2_score

### Load Dataset

In [9]:
data1 = pd.read_csv("student_data.csv")

### Info of the Dataset

In [11]:
data1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 395 entries, 0 to 394
Data columns (total 33 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   school      395 non-null    object
 1   sex         395 non-null    object
 2   age         395 non-null    int64
 3   address     395 non-null    object
 4   famsize     395 non-null    object
 5   Pstatus     395 non-null    object
 6   Medu        395 non-null    int64
 7   Fedu        395 non-null    int64
 8   Mjob        395 non-null    object
 9   Fjob        395 non-null    object
 10  reason      395 non-null    object
 11  guardian    395 non-null    object
 12  traveltime  395 non-null    int64
 13  studytime   395 non-null    int64
 14  failures    395 non-null    int64
 15  schoolsup   395 non-null    object
 16  famsup      395 non-null    object
 17  paid        395 non-null    object
 18  activities  395 non-null    object
 19  nursery     395 non-null    object
 20  higher      395 non-null    object
 21  internet    395 non-null    object
 22  romantic    395 non-null    object
 23  famrel      395 non-null    int64
 24  freetime    395 non-null    int64
 25  goout       395 non-null    int64
 26  Dalc        395 non-null    int64
 27  Walc        395 non-null    int64
 28  health      395 non-null    int64
 29  absences    395 non-null    int64
 30  G1          395 non-null    int64
 31  G2          395 non-null    int64
 32  G3          395 non-null    int64
dtypes: int64(16), object(17)
memory usage: 102.0+ KB

### These columns were dropped because they are not relevant

In [13]:
data1.drop(columns=['traveltime', 'schoolsup', 'famsup', 'paid', 'activities' , 'internet','famrel', 'romantic','famrel ', 'Dalc' , 'Walc', 'nursery', 'higher', 'sex','age','address','famsize','Pstatus',], errors='ignore', inplace=True)
data1

,school,Medu,Fedu,Mjob,Fjob,reason,guardian,studytime,failures,freetime,goout,health,absences,G1,G2,G3
0,GP,4,4,at_home,teacher,course,mother,2,0,3,4,3,6,5,6,6
1,GP,1,1,at_home,other,course,father,2,0,3,3,3,4,5,5,6
2,GP,1,1,at_home,other,other,mother,2,3,3,2,3,10,7,8,10
3,GP,4,2,health,services,home,mother,3,0,2,2,5,2,15,14,15
4,GP,3,3,other,other,home,father,2,0,3,2,5,4,6,10,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
390,MS,2,2,services,services,course,other,2,2,5,4,4,11,9,9,9
391,MS,3,1,services,services,course,mother,1,0,4,5,2,3,14,16,16
392,MS,1,1,other,other,course,other,1,3,5,3,3,3,10,8,7
393,MS,3,2,services,other,course,mother,1,0,4,1,5,0,11,12,10
394,MS,1,1,other,at_home,course,father,1,0,2,3,5,5,8,9,9

In [14]:
data1.describe()

,Medu,Fedu,studytime,failures,freetime,goout,health,absences,G1,G2,G3
count,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000
mean,2.749367,2.521519,2.035443,0.334177,3.235443,3.108861,3.554430,5.708861,10.908861,10.713924,10.415190
std,1.094735,1.088201,0.839240,0.743651,0.998862,1.113278,1.390303,8.003096,3.319195,3.761505,4.581443
min,0.000000,0.000000,1.000000,0.000000,1.000000,1.000000,1.000000,0.000000,3.000000,0.000000,0.000000
25%,2.000000,2.000000,1.000000,0.000000,3.000000,2.000000,3.000000,0.000000,8.000000,9.000000,8.000000
50%,3.000000,2.000000,2.000000,0.000000,3.000000,3.000000,4.000000,4.000000,11.000000,11.000000,11.000000
75%,4.000000,3.000000,2.000000,0.000000,4.000000,4.000000,5.000000,8.000000,13.000000,13.000000,14.000000
max,4.000000,4.000000,4.000000,3.000000,5.000000,5.000000,5.000000,75.000000,19.000000,19.000000,20.000000

In [15]:
data1.head()

,school,Medu,Fedu,Mjob,Fjob,reason,guardian,studytime,failures,freetime,goout,health,absences,G1,G2,G3
0,GP,4,4,at_home,teacher,course,mother,2,0,3,4,3,6,5,6,6
1,GP,1,1,at_home,other,course,father,2,0,3,3,3,4,5,5,6
2,GP,1,1,at_home,other,other,mother,2,3,3,2,3,10,7,8,10
3,GP,4,2,health,services,home,mother,3,0,2,2,5,2,15,14,15
4,GP,3,3,other,other,home,father,2,0,3,2,5,4,6,10,10

### The school column contains categorical values (GP, MS) which cannot be directly used in machine learning models.To convert these categories into numerical format, we use get_dummies() function .

In [17]:
pd.get_dummies(data1["school"],dtype=int)

     GP  MS
0     1   0
1     1   0
2     1   0
3     1   0
4     1   0
..   ..  ..
390   0   1
391   0   1
392   0   1
393   0   1
394   0   1

[395 rows x 2 columns]

### Checking missing value

In [19]:
data1.isnull().sum() # checking missing values

school       0
Medu         0
Fedu         0
Mjob         0
Fjob         0
reason       0
guardian     0
studytime    0
failures     0
freetime     0
goout        0
health       0
absences     0
G1           0
G2           0
G3           0
dtype: int64

In [28]:
# So, As we can see that there is no null value in the dataset

### Here, G3 Represents the final grade of students , which is our Target Variable.

In [31]:
y_data = data1["G3"]

### Removing the Target from the Dataset

In [34]:
x_data = data1.drop("G3", axis=1)

### we apply one-hot encoding to the entire feature dataset. This converts all categorical variables into numerical (0/1) format.

In [37]:
x_data = pd.get_dummies(x_data,dtype=int)
#This ensures that the dataset is fully prepared for machine learning models, which require numerical input.

In [39]:
print(x_data)

     Medu  Fedu  studytime  failures  freetime  goout  health  absences  G1  \
0       4     4          2         0         3      4       3         6   5
1       1     1          2         0         3      3       3         4   5
2       1     1          2         3         3      2       3        10   7
3       4     2          3         0         2      2       5         2  15
4       3     3          2         0         3      2       5         4   6
..    ...   ...        ...       ...       ...    ...     ...       ...  ..
390     2     2          2         2         5      4       4        11   9
391     3     1          1         0         4      5       2         3  14
392     1     1          1         3         5      3       3         3  10
393     3     2          1         0         4      1       5         0  11
394     1     1          1         0         2      3       5         5   8

     G2  ...  Fjob_other  Fjob_services  Fjob_teacher  reason_course  \
0     6  ...           0              0             1              1
1     5  ...           1              0             0              1
2     8  ...           1              0             0              0
3    14  ...           0              1             0              0
4    10  ...           1              0             0              0
..   ..  ...         ...            ...           ...            ...
390   9  ...           0              1             0              1
391  16  ...           0              1             0              1
392   8  ...           1              0             0              1
393  12  ...           1              0             0              1
394   9  ...           0              0             0              1

     reason_home  reason_other  reason_reputation  guardian_father  \
0              0             0                  0                0
1              0             0                  0                1
2              0             1                  0                0
3              1             0                  0                0
4              1             0                  0                1
..           ...           ...                ...              ...
390            0             0                  0                0
391            0             0                  0                0
392            0             0                  0                0
393            0             0                  0                0
394            0             0                  0                1

     guardian_mother  guardian_other
0                  1               0
1                  0               0
2                  1               0
3                  1               0
4                  0               0
..               ...             ...
390                0               1
391                1               0
392                0               1
393                1               0
394                0               0

[395 rows x 29 columns]

### Now, we apply feature scaling using StandardScaler to normalize the input features.

In [42]:
scaler = StandardScaler()
x_data_scaled = scaler.fit_transform(x_data)

### The dataset is split into training (80%) and testing (20%) sets. The training set is used to train the model, while the testing set is used to evaluate its performance with Predicted data of the Model.

In [45]:
x_train , x_test , y_train , y_test = train_test_split(x_data_scaled , y_data , test_size=0.2 , random_state = 0)

### The Linear Regression model is trained using the training data to learn the relationship between input features and the target variable.

In [48]:
modelv1 = LinearRegression()
modelv1.fit(x_train , y_train)

LinearRegression()

### Now, y_pred have the Predicted values of the model . So, now these predicted are used to evaluate the model's performance

In [51]:
y_pred = modelv1.predict(x_test)
print(y_pred)

[13.96760347 10.67072847 10.38166597 15.1619394  16.81916597 11.77033784
 12.67951753 10.77619722  8.58088472 13.79182222  7.45197847 14.62775972
 11.42658784  7.61213472 14.8572519  14.21565034 13.59650972  9.07111909
  9.26838472 14.79084565  5.81525972  3.46369722  6.00666597 15.02522065
 11.48322847 16.35432222  9.42854097 20.35627534 -0.67302153 13.08869722
 -1.68083403  6.66682222  7.83869722  5.49592378 12.32307222  9.81916597
 12.83772065 19.13947847  8.65510347 11.49494722  4.23811128 18.76447847
  8.17854097  8.20686128  9.80549409 -2.30974028 11.96174409  4.53791597
 11.76057222  6.47346284  8.97150972 18.19025972 11.83869722  7.49885347
 11.85822847  8.24885347  8.74494722 12.60432222 15.02522065 13.43244722
 13.40900972 12.91682222 13.58674409 15.45002534  8.49104097 15.91291597
 18.14338472 11.95393159  3.59065034  8.90803315  8.07307222 13.49494722
  7.35432222  4.31525972 12.83088472  8.18440034 10.62190034 18.45002534
  4.95979097]

### This displays the actual target values from the test dataset, which are used to compare with the predicted values.

In [54]:
print(y_test)

329    14
318    10
317     9
65     15
59     16
       ..
276     9
140     0
142    11
306    18
146     0
Name: G3, Length: 79, dtype: int64

### In this step, the performance of the Linear Regression model is evaluated using different metrics. Mean Absolute Error (MAE) measures the average error, Mean Squared Error (MSE) penalizes larger errors, and the R² Score indicates how well the model fits the data (values closer to 1 represent better performance).

## EVALUATION METRICS OF LINEAR REGRESSION :

In [58]:
print("EVALUATION METRICS OF LINEAR REGRESSION : ")
print("Mean Absolute Error = ",mean_absolute_error(y_test,y_pred))
print("Mean Square Error = ",mean_squared_error(y_test,y_pred))
print("R2 Score =",r2_score(y_test,y_pred))

EVALUATION METRICS OF LINEAR REGRESSION :
Mean Absolute Error =  1.5202385575854231
Mean Square Error =  5.758378327160266
R2 Score = 0.7912787681650393

# Decision Tree Algorithm

### Import Libraries

In [109]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sb 
import sklearn 

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier , plot_tree
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score , classification_report , confusion_matrix
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

### Load Dataset

In [111]:
data2 = pd.read_csv("student_data.csv")

### Info of the Dataset

In [113]:
data2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 395 entries, 0 to 394
Data columns (total 33 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   school      395 non-null    object
 1   sex         395 non-null    object
 2   age         395 non-null    int64
 3   address     395 non-null    object
 4   famsize     395 non-null    object
 5   Pstatus     395 non-null    object
 6   Medu        395 non-null    int64
 7   Fedu        395 non-null    int64
 8   Mjob        395 non-null    object
 9   Fjob        395 non-null    object
 10  reason      395 non-null    object
 11  guardian    395 non-null    object
 12  traveltime  395 non-null    int64
 13  studytime   395 non-null    int64
 14  failures    395 non-null    int64
 15  schoolsup   395 non-null    object
 16  famsup      395 non-null    object
 17  paid        395 non-null    object
 18  activities  395 non-null    object
 19  nursery     395 non-null    object
 20  higher      395 non-null    object
 21  internet    395 non-null    object
 22  romantic    395 non-null    object
 23  famrel      395 non-null    int64
 24  freetime    395 non-null    int64
 25  goout       395 non-null    int64
 26  Dalc        395 non-null    int64
 27  Walc        395 non-null    int64
 28  health      395 non-null    int64
 29  absences    395 non-null    int64
 30  G1          395 non-null    int64
 31  G2          395 non-null    int64
 32  G3          395 non-null    int64
dtypes: int64(16), object(17)
memory usage: 102.0+ KB

### Y1 contains the Targets of the Dataset

In [115]:
y1 = data2["G3"]          # target

### X1 contains the Features of the Dataset

In [117]:
x1 = data2.drop("G3", axis=1)  #features

### Categorical features are converted into numerical format using one-hot encoding

In [119]:
x1 = pd.get_dummies(x1, dtype=int) 
# This ensures that all input features are in a suitable form for machine learning models, which require numerical data. So,that model can understand.

### The dataset is split into training (80%) and testing (20%) sets. The training set is used to train the model, while the testing set is used to evaluate its performance with Predicted data of the Model.

In [123]:
x1_train,x1_test,y1_train,y1_test=train_test_split(x1,y1,test_size=0.2,random_state=0)

### The Decision Tree Classifier model is trained using the training data to learn the relationship between input features and the target variable.

In [125]:
dt_classifier = DecisionTreeClassifier(random_state = 42)  #Decision tree classifier
dt_classifier.fit(x1_train,y1_train)  #Train the model

DecisionTreeClassifier(random_state=42)

### Now, y_pred have the Predicted values of the model . So, now these predicted values are used to evaluate the model's performance.

In [156]:
y1_pred = dt_classifier.predict(x1_test) #make prediction using DT classifier
print(y1_pred)

[14 11 11 16 15 13 14 13 10 17  6 13 10  7 15 14 13  9  8 15  0  0  0 15
 12 16 10 19  0 13  0  8  8  5 12 11 13 18 12 10  5 19  7 10 10  0 13  0
 11  8  8 18 13  0 11  7  0 13 15 14 13 14 13 16 10 15 17 12  6  9  9 14
  8  0  9  8 11 18  0]

### This displays the actual target values from the test dataset, which are used to compare with the predicted values.

In [159]:
print(y1_test)

329    14
318    10
317     9
65     15
59     16
       ..
276     9
140     0
142    11
306    18
146     0
Name: G3, Length: 79, dtype: int64

### In this step, the performance of the Decision Tree model is evaluated using standard regression metrics. Mean Absolute Error (MAE) represents the average prediction error, Mean Squared Error (MSE) gives higher importance to larger errors, and the R² Score indicates how well the model explains the variability in the data.

## EVALUATION METRICS OF DECISION TREE :

In [162]:
print("EVALUATION METRICS OF DECISION TREE : ")
print("Mean Absolute Error = ",mean_absolute_error(y1_test,y1_pred))
print("Mean Square Error = ",mean_squared_error(y1_test,y1_pred))
print("R2 Score =",r2_score(y1_test,y1_pred))

EVALUATION METRICS OF DECISION TREE :
Mean Absolute Error =  1.4430379746835442
Mean Square Error =  7.443037974683544
R2 Score = 0.730215701989755

# Random Forest Algorithm

### Import Libraries

In [185]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn 

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier , plot_tree
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score , classification_report , confusion_matrix

### Load Dataset

In [224]:
data3 = pd.read_csv("student_data.csv")

### Info of the Dataset

In [227]:
data3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 395 entries, 0 to 394
Data columns (total 33 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   school      395 non-null    object
 1   sex         395 non-null    object
 2   age         395 non-null    int64
 3   address     395 non-null    object
 4   famsize     395 non-null    object
 5   Pstatus     395 non-null    object
 6   Medu        395 non-null    int64
 7   Fedu        395 non-null    int64
 8   Mjob        395 non-null    object
 9   Fjob        395 non-null    object
 10  reason      395 non-null    object
 11  guardian    395 non-null    object
 12  traveltime  395 non-null    int64
 13  studytime   395 non-null    int64
 14  failures    395 non-null    int64
 15  schoolsup   395 non-null    object
 16  famsup      395 non-null    object
 17  paid        395 non-null    object
 18  activities  395 non-null    object
 19  nursery     395 non-null    object
 20  higher      395 non-null    object
 21  internet    395 non-null    object
 22  romantic    395 non-null    object
 23  famrel      395 non-null    int64
 24  freetime    395 non-null    int64
 25  goout       395 non-null    int64
 26  Dalc        395 non-null    int64
 27  Walc        395 non-null    int64
 28  health      395 non-null    int64
 29  absences    395 non-null    int64
 30  G1          395 non-null    int64
 31  G2          395 non-null    int64
 32  G3          395 non-null    int64
dtypes: int64(16), object(17)
memory usage: 102.0+ KB

### Y2 Contains the Targets of the dataset

In [230]:
y2 = data3["G3"]    #Targets

### X2 Contains the Features of the Dataset

In [233]:
x2 = data3.drop("G3", axis=1)  #features

### Categorical features are converted into numerical format using one-hot encoding

In [237]:
x2 = pd.get_dummies(x2, dtype=int)

### The dataset is split into training (80%) and testing (20%) sets. The training set is used to train the model, while the testing set is used to evaluate its performance with Predicted data of the Model.

In [239]:
x2_train,x2_test,y2_train,y2_test=train_test_split(x2,y2,test_size=0.2,random_state=0)

### The Decision Tree Classifier model is trained using the training data to learn the relationship between input features and the target variable.

In [245]:
rf_classifier = RandomForestClassifier(random_state=42)   #Decision tree classifier

rf_classifier.fit(x2_train,y2_train)   #Train the model

RandomForestClassifier(random_state=42)

### Now, y2_pred have the Predicted values of the model . So, now these predicted values are used to evaluate the model's performance.

In [247]:
y2_pred = rf_classifier.predict(x2_test) #make prediction using DT classifier
print(y2_pred)

[15 12 11 15 15 14 11 10 10 16 10 11 11  6 15 13 11 10  9 15  0  0  0 15
 11 16 10 16  0 11  0 10  8  8 14 10 13 15 12 12 10 16  9  0 10  0 11  0
 11  0 10 18 10 10 11 11 10 13 15 13 13 14 13 15 10 15 14 13  6 10 10 13
  8  0  0 11 11 15  0]

### This displays the actual target values from the test dataset, which are used to compare with the predicted values.

In [249]:
print(y2_test)

329    14
318    10
317     9
65     15
59     16
       ..
276     9
140     0
142    11
306    18
146     0
Name: G3, Length: 79, dtype: int64

### In this step, the performance of the Decision Tree model is evaluated using standard regression metrics. Mean Absolute Error (MAE) represents the average prediction error, Mean Squared Error (MSE) gives higher importance to larger errors, and the R² Score indicates how well the model explains the variability in the data.

## EVALUATION METRICS OF DECISION TREE :

In [255]:
print("EVALUATION METRICS OF RANDOM FOREST : ")
print("Mean Absolute Error = ",mean_absolute_error(y2_test,y2_pred))
print("Mean Square Error = ",mean_squared_error(y2_test,y2_pred))
print("R2 Score =",r2_score(y2_test,y2_pred))

EVALUATION METRICS OF RANDOM FOREST :
Mean Absolute Error =  1.8481012658227849
Mean Square Error =  10.025316455696203
R2 Score = 0.6366170679862007